### ISSUE TITLE
Organization Page

### ISSUE THREAD

**Issue by iltempe** [timwis/jkan#96] opened 2016-04-16 19:45 UTC
Hi, 
in my page http://iltempe.github.io/opendatagentediprato/organizations/CFR/ I see not only the dataset of CFR organization but all datasets. This for all organization page. Can you help me? Is a bug? thanks

**Comment by timwis** [comment] 2016-04-16 21:51
Hi @iltempe, I discovered that bug yesterday when you reported the issue with organization links. It's caused by the same problem -- the lack of a `slug` property on github pages' version of jekyll. It should be fixed in the latest branch of `gh-pages`. If you go to your admin page and click Upgrade in the Maintenance section, you should be able to pull in those changes. Please re-open this issue if that doesn't fix it.

**Closed by timwis** 2016-04-16 21:51 UTC
